Fix stable/liberty branch
stable/liberty was failing with multiple issues, so these 3 are
squashed.

54c0c6a fixes this error seen starting glance-api:

 AttributeError: 'Opt' object has no attribute 'group'

b2484fd is a prereq for 0591868

0591868 fixes this error seen starting glance-api:

 AttributeError: 'AccessInfoV3' object has no attribute 'bind'

Fix deprecated options in oslo_config

Converting a keystoneauth Opt to an oslo_config Opt fails because we
convert the deprecated options to a real oslo_config Opt rather than a
DeprecatedOpt.

Orig-Change-Id: I1c86bec7cddcc5751e6584b381e60115b84e1d27
Closes-Bug: #1505906
(cherry picked from commit 54c0c6abe618c8fa3f2e7ce95811a2b8346c7c8d)

Copy AccessInfo tests from keystoneclient

There were some basic small issues with AccessInfo accessors and it
appears that the tests were never transferred across from
keystoneclient.

Copy those tests as closely as possible.

Orig-Change-Id: I391bf23097c5a8a176a50a938c04fa259df1de12
(cherry picked from commit b2484fdbf661d1404b8697eb11873829286fdecf)

Expose bind data via AccessInfo

The bind information is a standard part of the token data and can be
access from auth_token middleware so it should be exposed as part of the
AccessInfo object.

Change-Id: I45fc6eeed43f335aa1d771bdf1a11257432cb85c
(cherry picked from commit 4fd8531fd5e7ad6b2fc49d312b1104eefc66e311)