Use human readable exception messages
Currently, the exceptions are nothing if converted to strings.
The doc strings are human reable and useful to users, so use them.
Before:

    $ python examples/connection.py
    ERROR: Exception raised:
    $

After:

    $ python examples/connection.py
    ERROR: Exception raised: Could not find requested endpoint in Service Catalog.
    $

Change-Id: I1300e411c93bdfb17975e4f61e925b5b6474434c