Iterate over copy of session.adapters keys in Python2/3
Iterate over a copy of session.adapters keys in both Python 2.x and
Python 3.x.  In Python 3.5+, keys() is not a copy, and therefore
items can't be popped from it while iterating.
    RuntimeError: OrderedDict mutated during iteration
    https://bugs.python.org/issue24369
    https://hg.python.org/cpython/rev/0d8679858272

Change-Id: I038f1e8261fa6b29401e6c64db95f7480b35a598
Closes-Bug: #1502232